{{-- The page shell. Generated by @@viliha/vui-laravel. Do not edit. --}}
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" @class(['dark' => ($dark ?? false)])>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ $title ?? config('app.name') }}</title>
    {{-- One stylesheet. It carries the tokens, so a theme switch is a class on <html>, not a reload. --}}
    <link rel="stylesheet" href="{{ asset('vui/vui.css') }}" />
  </head>
  <body class="bg-background text-foreground">
    {{ $slot }}
    {{-- Deferred, and it is the only script: the families that need behaviour attach on DOMContentLoaded. --}}
    <script src="{{ asset('vui/vui.js') }}" defer></script>
  </body>
</html>
