{{-- accordion: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- accordion: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div data-slot="accordion" data-orientation="vertical">
  <div
    data-state="open"
    data-orientation="vertical"
    data-slot="accordion-item"
    class="vui-accordion-item"
  >
    <h3 data-orientation="vertical" data-state="open" class="flex">
      <button
        type="button"
        aria-controls="radix-_R_5_"
        aria-expanded="true"
        data-state="open"
        data-orientation="vertical"
        id="radix-_R_1_"
        data-slot="accordion-trigger"
        class="flex flex-1 items-start justify-between gap-4 rounded-md py-4 text-left text-sm font-medium transition-all outline-none hover:underline focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 [&[data-state=open]>svg]:rotate-180"
        data-radix-collection-item=""
      >
        Shipping<svg
          width="15"
          height="15"
          viewBox="0 0 15 15"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          class="vui-icon-plain vui-accordion-chevron"
        >
          <path
            d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z"
            fill="currentColor"
            fill-rule="evenodd"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </h3>
    <div
      data-state="open"
      id="radix-_R_5_"
      role="region"
      aria-labelledby="radix-_R_1_"
      data-orientation="vertical"
      data-slot="accordion-content"
      class="overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
      style="
        --radix-accordion-content-height: var(--radix-collapsible-content-height);
        --radix-accordion-content-width: var(--radix-collapsible-content-width);
        --vui-accordion-height: var(--radix-accordion-content-height);
      "
    >
      <div class="vui-accordion-content-inner">Free above 50, three days.</div>
    </div>
  </div>
  <div
    data-state="closed"
    data-orientation="vertical"
    data-slot="accordion-item"
    class="vui-accordion-item"
  >
    <h3 data-orientation="vertical" data-state="closed" class="flex">
      <button
        type="button"
        aria-expanded="false"
        data-state="closed"
        data-orientation="vertical"
        id="radix-_R_2_"
        data-slot="accordion-trigger"
        class="flex flex-1 items-start justify-between gap-4 rounded-md py-4 text-left text-sm font-medium transition-all outline-none hover:underline focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 [&[data-state=open]>svg]:rotate-180"
        data-radix-collection-item=""
      >
        Returns<svg
          width="15"
          height="15"
          viewBox="0 0 15 15"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          class="vui-icon-plain vui-accordion-chevron"
        >
          <path
            d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z"
            fill="currentColor"
            fill-rule="evenodd"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </h3>
    <div
      data-state="closed"
      id="radix-_R_6_"
      hidden=""
      role="region"
      aria-labelledby="radix-_R_2_"
      data-orientation="vertical"
      data-slot="accordion-content"
      class="overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
      style="
        --radix-accordion-content-height: var(--radix-collapsible-content-height);
        --radix-accordion-content-width: var(--radix-collapsible-content-width);
        --vui-accordion-height: var(--radix-accordion-content-height);
      "
    ></div>
  </div>
</div>
