{{-- alert-dialog: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- alert-dialog: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<button
  type="button"
  class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-transparent bg-[var(--button-primary)] text-[var(--button-primary-foreground)] shadow-[var(--button-shadow)] hover:bg-[var(--button-primary-hover)] [&_svg]:border-[var(--button-primary-hover)] h-8 px-3"
  data-vui-open="alert-dialog-demo"
>
  Delete organization
</button>
<dialog
  id="alert-dialog-demo"
  class="group/alert-dialog-content fixed top-[50%] left-[50%] z-[80] grid w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] gap-4 rounded-lg border bg-background p-6 shadow-lg duration-200 data-[size=sm]:max-w-xs data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 data-[size=default]:sm:max-w-lg"
  data-size="default"
  role="alertdialog"
  aria-labelledby="alert-dialog-demo-title"
  aria-describedby="alert-dialog-demo-description"
>
  <div
    class="flex flex-col gap-1.5 text-center sm:group-data-[size=default]/alert-dialog-content:text-left"
  >
    <h2 class="vui-alert-dialog-title" id="alert-dialog-demo-title">Delete Northwind Traders?</h2>
    <p class="vui-alert-dialog-description" id="alert-dialog-demo-description">
      Eleven branches and 1,204 employees lose access immediately. This cannot be undone.
    </p>
  </div>
  <div class="vui-alert-dialog-footer">
    <form method="dialog">
      <button
        type="submit"
        class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-8 px-3"
      >
        Cancel
      </button>
    </form>
    <button
      type="button"
      class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 bg-destructive text-destructive-foreground hover:bg-destructive/90 h-8 px-3"
    >
      Delete
    </button>
  </div>
</dialog>
