{{-- alert: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- alert: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  data-slot="alert"
  role="alert"
  class="relative grid w-full grid-cols-[0_1fr] items-start rounded-xl border p-4 text-sm has-[>svg]:grid-cols-[calc(var(--spacing)*6)_1fr] has-[>svg]:gap-x-3 [&>svg]:size-6 [&>svg]:-translate-y-0.5 [&>svg]:text-current bg-card text-card-foreground"
>
  <div data-slot="alert-title" class="vui-alert-title">Payment method expires soon</div>
  <div
    data-slot="alert-description"
    class="col-start-2 grid justify-items-start gap-1 text-sm text-muted-foreground [&_p]:leading-relaxed"
  >
    Update it before the next billing date.
  </div>
</div>
