{{-- aspect-ratio: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- aspect-ratio: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  style="position: relative; width: 100%; padding-bottom: 56.25%"
  data-radix-aspect-ratio-wrapper=""
>
  <div data-slot="aspect-ratio" style="position: absolute; top: 0; right: 0; bottom: 0; left: 0">
    <div class="size-full rounded-md bg-muted"></div>
  </div>
</div>
