{{-- avatar: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- avatar: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div data-slot="avatar" class="vui-avatar-root">
  <div data-slot="avatar-fallback" class="vui-avatar-fallback">AI</div>
</div>
