{{-- badge: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- badge: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<span class="vui-badge border-transparent bg-success/10 text-success">Active</span>
