{{-- breadcrumb: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- breadcrumb: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<nav aria-label="breadcrumb" data-slot="breadcrumb">
  <ol data-slot="breadcrumb-list" class="vui-breadcrumb-list">
    <li data-slot="breadcrumb-item" class="vui-breadcrumb-item">
      <a
        data-slot="breadcrumb-link"
        class="transition-colors hover:text-foreground"
        href="/dashboard"
        >Home</a
      >
    </li>
    <li
      data-slot="breadcrumb-separator"
      role="presentation"
      aria-hidden="true"
      class="[&>svg]:size-3.5"
    >
      <svg
        width="15"
        height="15"
        viewBox="0 0 15 15"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        class="vui-icon-plain"
      >
        <path
          d="M6.1584 3.13508C6.35985 2.94621 6.67627 2.95642 6.86514 3.15788L10.6151 7.15788C10.7954 7.3502 10.7954 7.64949 10.6151 7.84182L6.86514 11.8418C6.67627 12.0433 6.35985 12.0535 6.1584 11.8646C5.95694 11.6757 5.94673 11.3593 6.1356 11.1579L9.565 7.49985L6.1356 3.84182C5.94673 3.64036 5.95694 3.32394 6.1584 3.13508Z"
          fill="currentColor"
          fill-rule="evenodd"
          clip-rule="evenodd"
        ></path>
      </svg>
    </li>
    <li data-slot="breadcrumb-item" class="vui-breadcrumb-item">
      <span
        data-slot="breadcrumb-page"
        role="link"
        aria-disabled="true"
        aria-current="page"
        class="vui-breadcrumb-page"
        >Organizations</span
      >
    </li>
  </ol>
</nav>
