{{-- button: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- button: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<button
  type="button"
  class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-7 rounded-sm px-2.5"
>
  Save changes
</button>
