{{-- card: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- card: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div data-slot="card" class="vui-card">
  <div data-slot="card-header" class="vui-card-header">
    <h3 data-slot="card-title" class="vui-card-title">Northwind Traders</h3>
    <p data-slot="card-description" class="vui-card-description">Trialing until 4 September</p>
  </div>
  <div data-slot="card-content" class="vui-card-content">Eleven branches across two markets.</div>
</div>
