{{-- cascading-combobox: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- cascading-combobox: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<div class="flex gap-2">
  <select
    class="flex h-11 w-full items-center justify-between gap-2 rounded-lg border border-input bg-background px-4 text-sm transition-colors hover:bg-accent/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive"
    id="cascade-region"
  >
    <option value="emea" selected="">EMEA</option>
    <option value="apac">APAC</option></select
  ><select
    class="flex h-11 w-full items-center justify-between gap-2 rounded-lg border border-input bg-background px-4 text-sm transition-colors hover:bg-accent/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive"
    data-vui-parent="cascade-region"
  >
    <option value="de" data-vui-when="emea">Germany</option>
    <option value="nl" data-vui-when="emea">Netherlands</option>
    <option value="sg" data-vui-when="apac">Singapore</option>
  </select>
</div>
