{{-- chart: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- chart: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<figure class="vui-chart-native-figure">
  <svg viewBox="0 0 320 120" class="vui-chart-native-svg" role="img" aria-label="Revenue by month">
    <polyline
      points="8.0,54.5 109.3,32.6 210.7,8.0 312.0,28.5"
      fill="none"
      stroke="var(--chart-1)"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></polyline>
    <polygon
      points="8,112 8.0,54.5 109.3,32.6 210.7,8.0 312.0,28.5 312,112"
      fill="var(--chart-1)"
      fill-opacity="0.15"
    ></polygon>
  </svg>
  <figcaption class="vui-chart-native-caption">Revenue by month</figcaption>
</figure>
