{{-- checkbox: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- checkbox: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<input
  type="checkbox"
  class="size-4 shrink-0 cursor-pointer rounded border-input accent-[var(--button-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:ring-2 aria-invalid:ring-destructive"
  checked=""
/>
