{{-- collapsible: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- collapsible: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<details class="vui-collapsible-native-root">
  <summary
    class="flex cursor-pointer list-none items-center justify-between gap-2 px-3 py-2 font-medium transition-colors hover:bg-accent/40"
  >
    Branch details<span aria-hidden="true">+</span>
  </summary>
  <div class="vui-collapsible-native-content">
    Eleven branches across two markets, opened between 2019 and 2024.
  </div>
</details>
