{{-- combobox: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- combobox: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<input
  class="flex h-11 w-full items-center justify-between gap-2 rounded-lg border border-input bg-background px-4 text-sm transition-colors hover:bg-accent/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive"
  list="combobox-demo-options"
  placeholder="Search countries"
  name="country"
/><datalist id="combobox-demo-options">
  <option value="Germany"></option>
  <option value="Netherlands"></option>
  <option value="Singapore"></option>
  <option value="United Kingdom"></option>
</datalist>
