{{-- command: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- command: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div tabindex="-1" data-slot="command" class="vui-command-root" cmdk-root="">
  <label
    cmdk-label=""
    for="radix-_R_0H2_"
    id="radix-_R_0H1_"
    style="
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border-width: 0;
    "
  ></label>
  <div data-slot="command-input-wrapper" class="vui-command-input-row">
    <svg
      width="15"
      height="15"
      viewBox="0 0 15 15"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      class="vui-icon-plain vui-command-input-icon"
    >
      <path
        d="M10 6.5C10 8.433 8.433 10 6.5 10C4.567 10 3 8.433 3 6.5C3 4.567 4.567 3 6.5 3C8.433 3 10 4.567 10 6.5ZM9.30884 10.0159C8.53901 10.6318 7.56251 11 6.5 11C4.01472 11 2 8.98528 2 6.5C2 4.01472 4.01472 2 6.5 2C8.98528 2 11 4.01472 11 6.5C11 7.56251 10.6318 8.53901 10.0159 9.30884L12.8536 12.1464C13.0488 12.3417 13.0488 12.6583 12.8536 12.8536C12.6583 13.0488 12.3417 13.0488 12.1464 12.8536L9.30884 10.0159Z"
        fill="currentColor"
        fill-rule="evenodd"
        clip-rule="evenodd"
      ></path></svg
    ><input
      data-slot="command-input"
      class="flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-hidden placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50"
      placeholder="Search organizations"
      cmdk-input=""
      autocomplete="off"
      autocorrect="off"
      spellcheck="false"
      aria-autocomplete="list"
      role="combobox"
      aria-expanded="true"
      aria-controls="radix-_R_0_"
      aria-labelledby="radix-_R_0H1_"
      id="radix-_R_0H2_"
      type="text"
      value=""
    />
  </div>
  <div
    data-slot="command-list"
    class="vui-command-list"
    cmdk-list=""
    role="listbox"
    tabindex="-1"
    aria-label="Suggestions"
    id="radix-_R_0_"
  >
    <div cmdk-list-sizer="">
      <div data-slot="command-empty" class="vui-command-empty" cmdk-empty="" role="presentation">
        No results.
      </div>
      <div
        data-slot="command-group"
        class="overflow-hidden p-1 text-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground"
        cmdk-group=""
        role="presentation"
      >
        <div cmdk-group-heading="" aria-hidden="true" id="radix-_R_2lH1_">Recent</div>
        <div cmdk-group-items="" role="group" aria-labelledby="radix-_R_2lH1_">
          <div
            data-slot="command-item"
            class="relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 data-[disabled='']:pointer-events-none data-[disabled='']:opacity-50 data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground"
            id="radix-_R_1ml_"
            cmdk-item=""
            role="option"
            aria-disabled="false"
            aria-selected="false"
            data-disabled="false"
            data-selected="false"
          >
            Acme Industrial
          </div>
          <div
            data-slot="command-item"
            class="relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 data-[disabled='']:pointer-events-none data-[disabled='']:opacity-50 data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground"
            id="radix-_R_2ml_"
            cmdk-item=""
            role="option"
            aria-disabled="false"
            aria-selected="false"
            data-disabled="false"
            data-selected="false"
          >
            Northwind Traders
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
