{{-- command-palette: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- command-palette: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-palette-overlay">
  <div
    role="dialog"
    aria-modal="true"
    aria-label="Command palette"
    class="vui-pop-in flex max-h-[70vh] w-full max-w-lg flex-col overflow-hidden rounded-xl border border-border bg-popover text-popover-foreground shadow-2xl"
    style="--vui-pop-origin: top center"
  >
    <div class="vui-palette-search-row">
      <svg
        viewBox="0 0 15 15"
        aria-hidden="true"
        class="vui-palette-item-hint"
        fill="none"
        stroke="currentColor"
        stroke-width="1.2"
      >
        <circle cx="6.5" cy="6.5" r="4"></circle>
        <path d="M9.5 9.5 L13 13" stroke-linecap="round"></path></svg
      ><input
        placeholder="Search…"
        aria-label="Search…"
        class="h-11 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        value=""
      /><kbd class="vui-kbd-base vui-palette-search-icon">Esc</kbd>
    </div>
    <div class="vui-palette-list">
      <div class="mb-1 last:mb-0">
        <button
          type="button"
          data-active="true"
          class="flex w-full items-center gap-2.5 rounded-md px-2 py-1.5 text-left text-sm transition-colors data-[active=true]:bg-accent data-[active=true]:text-accent-foreground"
        >
          <span class="vui-palette-item-label">Go to organizations</span></button
        ><button
          type="button"
          data-active="false"
          class="flex w-full items-center gap-2.5 rounded-md px-2 py-1.5 text-left text-sm transition-colors data-[active=true]:bg-accent data-[active=true]:text-accent-foreground"
        >
          <span class="vui-palette-item-label">New organization</span>
        </button>
      </div>
    </div>
  </div>
</div>
