{{-- confirm-dialog: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- confirm-dialog: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  class="vui-overlay-in fixed inset-0 z-[70] flex items-center justify-center p-4 bg-foreground/25 supports-[backdrop-filter]:backdrop-blur-md"
>
  <div
    role="dialog"
    data-vui-panel=""
    aria-modal="true"
    aria-label="Delete Northwind Traders?"
    tabindex="-1"
    style="--vui-pop-origin: center"
    class="vui-pop-in w-full overflow-hidden rounded-lg border border-border bg-background shadow-xl max-w-sm"
  >
    <button
      type="button"
      aria-label="Close dialog"
      class="absolute top-3 right-3 z-10 grid size-8 cursor-pointer place-items-center rounded-full bg-muted text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
      data-vui-dismiss=""
    >
      <svg viewBox="0 0 24 24" aria-hidden="true" class="size-5" fill="currentColor">
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M6.04 16.54a1 1 0 1 0 1.42 1.42L12 13.41l4.54 4.55a1 1 0 0 0 1.42-1.42L13.41 12l4.55-4.54a1 1 0 0 0-1.42-1.42L12 10.59 7.46 6.04a1 1 0 0 0-1.42 1.42L10.59 12l-4.55 4.54Z"
        ></path>
      </svg>
    </button>
    <div class="vui-dialog-header"><h2 class="vui-dialog-title">Delete Northwind Traders?</h2></div>
    <div class="vui-dialog-body vui-confirm-dialog-description">
      Eleven branches lose access immediately. This cannot be undone.
    </div>
    <div class="vui-dialog-footer">
      <button
        type="button"
        class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-8 px-3"
      >
        Cancel</button
      ><button
        type="button"
        class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 bg-destructive text-destructive-foreground hover:bg-destructive/90 h-8 px-3 [&_svg]:border-white/30"
      >
        Delete
      </button>
    </div>
  </div>
</div>
