{{-- data-table: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- data-table: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-dt-root">
  <div class="vui-dt-frame">
    <table class="vui-table-root">
      <caption class="vui-table-caption">
        Invoices
      </caption>
      <thead class="[&_tr]:border-b">
        <tr class="border-b border-border transition-colors hover:bg-muted/50 vui-dt-head-row">
          <th
            class="h-8 border-r border-border px-3 align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
            aria-sort="none"
          ></th>
          <th
            class="h-8 border-r border-border px-3 align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
            aria-sort="none"
          ></th>
          <th
            class="h-8 border-r border-border px-3 align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
            aria-sort="none"
          ></th>
          <th
            class="h-8 border-r border-border px-3 align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
            aria-sort="none"
          ></th>
        </tr>
      </thead>
      <tbody>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Northwind Traders
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            paid
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2025-12-31T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            250
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Contoso
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            pending
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-02-07T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            387
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Fabrikam
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            overdue
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-03-14T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            524
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Adventure Works
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            paid
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-04-21T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            661
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Tailspin Toys
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            pending
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-05-01T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            798
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Wide World Importers
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            overdue
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-06-08T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            935
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Proseware
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            paid
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-07-15T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            1072
          </td>
        </tr>
        <tr class="border-b border-border transition-colors hover:bg-muted/50">
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            Northwind Traders
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            pending
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            2026-08-22T17:00:00.000Z
          </td>
          <td
            class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-left"
          >
            1209
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
