{{-- dropdown-menu: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- dropdown-menu: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<details class="relative inline-block">
  <summary class="vui-dropdown-trigger list-none">Actions</summary>
  <div
    class="vui-pop-in z-[200] min-w-52 overflow-hidden rounded-md border border-border bg-popover text-left text-sm font-normal text-popover-foreground shadow-md absolute top-full left-0 mt-1"
  >
    <p class="vui-dropdown-label">Organization</p>
    <button
      type="button"
      class="flex w-full cursor-pointer items-center gap-2 border-b border-border px-3 py-2 text-left last:border-b-0 hover:bg-accent hover:text-accent-foreground aria-disabled:cursor-not-allowed aria-disabled:opacity-50 aria-disabled:hover:bg-transparent aria-disabled:hover:text-inherit"
    >
      Edit</button
    ><button
      type="button"
      class="flex w-full cursor-pointer items-center gap-2 border-b border-border px-3 py-2 text-left last:border-b-0 hover:bg-accent hover:text-accent-foreground aria-disabled:cursor-not-allowed aria-disabled:opacity-50 aria-disabled:hover:bg-transparent aria-disabled:hover:text-inherit"
    >
      Duplicate
    </button>
  </div>
</details>
