{{-- field-grid: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- field-grid: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-field-grid-root">
  <div class="vui-field-row">
    <label for="legal-name" class="vui-field-label"
      >Legal name<svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2.5"
        stroke-linecap="round"
        class="vui-required-mark"
        aria-label="required"
      >
        <line x1="12" y1="5" x2="12" y2="19"></line>
        <line x1="5.5" y1="8.5" x2="18.5" y2="15.5"></line>
        <line x1="18.5" y1="8.5" x2="5.5" y2="15.5"></line></svg
    ></label>
    <div class="vui-field-control">
      <div class="vui-field-control-inner">
        <input
          class="flex h-11 w-full rounded-lg border border-input bg-background px-4 py-2.5 text-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive disabled:cursor-not-allowed disabled:opacity-50 file:border-0 file:bg-transparent file:font-medium"
          id="legal-name"
          value="Northwind Traders"
        />
      </div>
    </div>
  </div>
  <div class="vui-field-row">
    <label for="notes" class="vui-field-label vui-field-label-multiline">Notes</label>
    <div class="vui-field-control">
      <div class="vui-field-control-inner">
        <textarea
          data-slot="textarea"
          class="flex field-sizing-content min-h-24 w-full rounded-lg border border-input bg-transparent px-4 py-2.5 text-sm shadow-xs transition-[color,box-shadow] outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 md:text-sm dark:bg-input/30 dark:aria-invalid:ring-destructive/40"
          id="notes"
          rows="3"
        ></textarea>
      </div>
      <p class="vui-field-hint">Shown on the invoice.</p>
    </div>
  </div>
</div>
