{{-- form-actions: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- form-actions: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-form-footer-bar">
  <div class="vui-form-footer">
    <button
      type="button"
      class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-8 px-3"
    >
      Cancel</button
    ><button
      type="submit"
      class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-transparent bg-[var(--button-primary)] text-[var(--button-primary-foreground)] shadow-[var(--button-shadow)] hover:bg-[var(--button-primary-hover)] [&_svg]:border-[var(--button-primary-hover)] h-8 px-3"
    >
      Save
    </button>
  </div>
</div>
