{{-- hover-card: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- hover-card: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<span class="group relative inline-block"
  ><a href="./index.html" class="underline underline-offset-4">Northwind Traders</a
  ><span
    class="z-[210] w-64 origin-(--radix-hover-card-content-transform-origin) rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-hidden data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 absolute top-full left-0 mt-2 hidden group-hover:block group-focus-within:block"
    >Eleven branches across two markets, trialing until 4 September.</span
  ></span
>
