{{-- input: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- input: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<input
  class="flex h-11 w-full rounded-lg border border-input bg-background px-4 py-2.5 text-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive disabled:cursor-not-allowed disabled:opacity-50 file:border-0 file:bg-transparent file:font-medium"
  placeholder="you@example.com"
/>
