{{-- input-otp: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- input-otp: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<div class="flex items-center gap-2 has-disabled:opacity-50">
  <div class="vui-input-otp-group">
    <input
      maxlength="1"
      inputmode="numeric"
      autocomplete="one-time-code"
      aria-label="Digit 1"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    /><input
      maxlength="1"
      inputmode="numeric"
      aria-label="Digit 2"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    /><input
      maxlength="1"
      inputmode="numeric"
      aria-label="Digit 3"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    /><input
      maxlength="1"
      inputmode="numeric"
      aria-label="Digit 4"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    /><input
      maxlength="1"
      inputmode="numeric"
      aria-label="Digit 5"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    /><input
      maxlength="1"
      inputmode="numeric"
      aria-label="Digit 6"
      class="relative flex h-9 w-9 items-center justify-center border-y border-r border-input text-center text-sm shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md focus:z-10 focus:border-ring focus:ring-[3px] focus:ring-ring/50 aria-invalid:border-destructive"
    />
  </div>
</div>
