{{-- kbd: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- kbd: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<kbd class="vui-kbd-base">⌘K</kbd>
