{{-- label: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- label: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<label
  data-slot="label"
  class="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50"
  for="email"
  >Email</label
>
