{{-- list: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- list: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<ul class="vui-list-root divide-y divide-border">
  <li class="vui-list-item">Northwind Retail</li>
  <li class="vui-list-item">Sakura Foods</li>
  <li class="vui-list-item">Alpine Logistics</li>
</ul>
