{{-- menu: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- menu: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div data-slot="menu" role="menu" class="vui-menu-root">
  <p class="vui-menu-section">Workspace</p>
  <button
    role="menuitem"
    class="flex w-full items-center gap-2.5 border-b border-border px-3 py-2 text-left transition-colors last:border-b-0 hover:bg-accent"
    type="button"
  >
    Organizations</button
  ><button
    role="menuitem"
    class="flex w-full items-center gap-2.5 border-b border-border px-3 py-2 text-left transition-colors last:border-b-0 hover:bg-accent"
    type="button"
  >
    Branches
  </button>
</div>
