{{-- organization-profile: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- organization-profile: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-brand-asset-root">
  <div class="vui-brand-asset-row">
    <div class="vui-brand-asset-box h-12 w-24"><span class="vui-brand-asset-empty">None</span></div>
    <div class="vui-brand-asset-actions">
      <button
        type="button"
        class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-7 rounded-sm px-2.5"
      >
        Upload</button
      ><input type="file" accept="image/*" class="vui-brand-asset-input" />
    </div>
  </div>
</div>
