{{-- page: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- page: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-page-root">
  <div class="vui-page-header">
    <div class="vui-breadcrumbs-root">
      <nav aria-label="Breadcrumb" class="vui-breadcrumbs-nav">
        <span class="vui-breadcrumbs-crumb"><span class="vui-breadcrumbs-current">Home</span></span>
      </nav>
    </div>
    <div class="vui-page-actions">
      <button
        type="button"
        class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-7 rounded-sm px-2.5"
      >
        New organization
      </button>
    </div>
  </div>
  <div class="vui-page-scroll">
    <div class="vui-page-content">
      <div data-slot="card" class="vui-card">
        <div data-slot="card-content" class="vui-card-content">
          The page body scrolls; the header does not.
        </div>
      </div>
    </div>
  </div>
</div>
