{{-- progress: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- progress: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  aria-valuemax="100"
  aria-valuemin="0"
  aria-valuenow="62"
  aria-valuetext="62%"
  role="progressbar"
  data-state="loading"
  data-value="62"
  data-max="100"
  data-slot="progress"
  class="vui-progress-root"
>
  <div
    data-state="loading"
    data-value="62"
    data-max="100"
    data-slot="progress-indicator"
    class="vui-progress-indicator"
    style="transform: translateX(-38%)"
  ></div>
</div>
