{{-- radio-group: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- radio-group: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  role="radiogroup"
  aria-required="false"
  dir="ltr"
  data-slot="radio-group"
  class="vui-radio-group-root"
  tabindex="-1"
  style="outline: none"
>
  <div class="flex items-center gap-2">
    <button
      type="button"
      role="radio"
      aria-checked="true"
      data-state="checked"
      value="monthly"
      data-slot="radio-group-item"
      class="aspect-square size-5 shrink-0 rounded-full border border-input text-primary shadow-xs transition-[color,background-color,border-color,box-shadow] outline-none data-[state=checked]:border-primary data-[state=checked]:bg-primary focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:bg-input/30 dark:aria-invalid:ring-destructive/40"
      id="monthly"
      tabindex="-1"
      data-radix-collection-item=""
    >
      <span data-state="checked" data-slot="radio-group-indicator" class="vui-radio-group-indicator"
        ><span class="vui-radio-group-dot"></span
      ></span></button
    ><input
      type="radio"
      aria-hidden="true"
      tabindex="-1"
      style="
        position: absolute;
        pointer-events: none;
        opacity: 0;
        margin: 0;
        transform: translateX(-100%);
      "
      checked=""
      value="monthly"
    /><label
      data-slot="label"
      class="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50"
      for="monthly"
      >Monthly</label
    >
  </div>
  <div class="flex items-center gap-2">
    <button
      type="button"
      role="radio"
      aria-checked="false"
      data-state="unchecked"
      value="yearly"
      data-slot="radio-group-item"
      class="aspect-square size-5 shrink-0 rounded-full border border-input text-primary shadow-xs transition-[color,background-color,border-color,box-shadow] outline-none data-[state=checked]:border-primary data-[state=checked]:bg-primary focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:bg-input/30 dark:aria-invalid:ring-destructive/40"
      id="yearly"
      tabindex="-1"
      data-radix-collection-item=""
    ></button
    ><input
      type="radio"
      aria-hidden="true"
      tabindex="-1"
      style="
        position: absolute;
        pointer-events: none;
        opacity: 0;
        margin: 0;
        transform: translateX(-100%);
      "
      value="yearly"
    /><label
      data-slot="label"
      class="flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50"
      for="yearly"
      >Yearly</label
    >
  </div>
</div>
