{{-- required-mark: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- required-mark: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<svg
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2.5"
  stroke-linecap="round"
  class="vui-required-mark"
  aria-label="required"
>
  <line x1="12" y1="5" x2="12" y2="19"></line>
  <line x1="5.5" y1="8.5" x2="18.5" y2="15.5"></line>
  <line x1="18.5" y1="8.5" x2="5.5" y2="15.5"></line>
</svg>
