{{-- scroll-area: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- scroll-area: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  dir="ltr"
  data-slot="scroll-area"
  class="vui-scroll-area-root h-24"
  style="
    position: relative;
    --radix-scroll-area-corner-width: 0px;
    --radix-scroll-area-corner-height: 0px;
  "
>
  <style>
    [data-radix-scroll-area-viewport] {
      scrollbar-width: none;
      -ms-overflow-style: none;
      -webkit-overflow-scrolling: touch;
    }
    [data-radix-scroll-area-viewport]::-webkit-scrollbar {
      display: none;
    }
  </style>
  <div
    data-radix-scroll-area-viewport=""
    data-slot="scroll-area-viewport"
    class="size-full rounded-[inherit] transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1"
    style="overflow-x: hidden; overflow-y: hidden"
  >
    <div style="min-width: 100%; display: table">
      <p>A long region that scrolls inside its own frame.</p>
    </div>
  </div>
</div>
