{{-- select: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- select: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<select
  class="flex h-11 w-full items-center justify-between gap-2 rounded-lg border border-input bg-background px-4 text-sm transition-colors hover:bg-accent/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive"
>
  <option value="">Any status</option>
  <option value="active" selected="">Active</option>
  <option value="trial">Trial</option>
  <option value="suspended">Suspended</option>
</select>
