{{-- separator: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- separator: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div
  data-orientation="horizontal"
  role="none"
  data-slot="separator"
  class="shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px"
></div>
