{{-- skeleton: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- skeleton: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div data-slot="skeleton" class="vui-skeleton h-4 w-32"></div>
