{{-- slider: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- slider: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<input
  type="range"
  min="0"
  max="100"
  aria-label="Volume"
  class="h-1.5 w-full cursor-pointer appearance-none rounded-full bg-muted accent-[var(--button-primary)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring disabled:cursor-not-allowed disabled:opacity-50"
  value="50"
/>
