{{-- table: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- table: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<table class="vui-table-root">
  <thead class="[&_tr]:border-b">
    <tr class="border-b border-border transition-colors hover:bg-muted/50">
      <th
        class="h-8 border-r border-border px-3 text-left align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0"
      >
        Organization
      </th>
      <th
        class="h-8 border-r border-border px-3 text-left align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0"
      >
        Country
      </th>
      <th
        class="h-8 border-r border-border px-3 align-middle font-semibold text-foreground last:border-r-0 [&:has([role=checkbox])]:pr-0 text-right"
      >
        Employees
      </th>
    </tr>
  </thead>
  <tbody>
    <tr class="border-b border-border transition-colors hover:bg-muted/50">
      <td
        class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0"
      >
        Acme Industrial
      </td>
      <td
        class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0"
      >
        Germany
      </td>
      <td
        class="border-r border-border px-3 py-1.5 align-middle last:border-r-0 [&:has([role=checkbox])]:pr-0 text-right tabular-nums"
      >
        1,204
      </td>
    </tr>
  </tbody>
</table>
