{{-- textarea: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- textarea: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<textarea
  data-slot="textarea"
  class="flex field-sizing-content min-h-24 w-full rounded-lg border border-input bg-transparent px-4 py-2.5 text-sm shadow-xs transition-[color,box-shadow] outline-none placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 md:text-sm dark:bg-input/30 dark:aria-invalid:ring-destructive/40"
  rows="3"
  placeholder="Notes"
></textarea>
