{{-- toast: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- toast: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<div
  class="pointer-events-none fixed inset-x-0 bottom-0 z-[250] flex flex-col items-end gap-2 p-4 sm:left-auto sm:right-0 sm:max-w-sm"
  aria-live="polite"
>
  <div
    class="vui-toast-in pointer-events-auto flex w-full items-start gap-3 rounded-lg border border-border bg-background p-4 shadow-lg"
    data-vui-toast="true"
  >
    <div class="vui-toast-body">
      <p class="vui-toast-title">Organization saved</p>
      <p class="vui-toast-description">Northwind Traders was updated.</p>
    </div>
    <button
      type="button"
      class="shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
      data-vui-dismiss="true"
      aria-label="Dismiss"
    >
      ×
    </button>
  </div>
</div>
