{{-- toggle: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- toggle: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<button
  type="button"
  aria-pressed="false"
  data-state="off"
  data-slot="toggle"
  class="inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-[color,box-shadow] outline-none hover:bg-muted hover:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 bg-transparent h-9 min-w-9 px-2"
>
  Bold
</button>
