{{-- tooltip: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- tooltip: a native equivalent wearing the shared classes, because React builds this at runtime, by scripts/build-components.tsx. Do not edit. -->
<span class="group relative inline-block"
  ><button
    type="button"
    class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-8 px-3"
    aria-describedby="tooltip-demo"
  >
    Save</button
  ><span
    class="vui-fade-in w-fit max-w-xs text-balance rounded-md border border-border bg-popover px-3 py-1.5 text-xs text-popover-foreground shadow-md absolute top-full left-0 mt-2 hidden group-hover:block group-focus-within:block"
    role="tooltip"
    id="tooltip-demo"
    >Save changes</span
  ></span
>
