{{-- wizard: generated by @viliha/vui-laravel from the React source. Do not edit. --}}
<!-- wizard: rendered from the React component, by scripts/build-components.tsx. Do not edit. -->
<div class="vui-wizard-root">
  <div class="vui-wizard-header">
    <ol class="vui-steps-root" aria-label="Step 2 of 3">
      <li class="vui-steps-item">
        <span
          class="vui-steps-marker-base border-transparent bg-[var(--button-primary)] text-[var(--button-primary-foreground)]"
          ><svg
            width="15"
            height="15"
            viewBox="0 0 15 15"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="vui-steps-check-icon"
          >
            <path
              d="M11.4669 3.72684C11.7558 3.91574 11.8369 4.30308 11.648 4.59198L7.39799 11.092C7.29783 11.2452 7.13556 11.3467 6.95402 11.3699C6.77247 11.3931 6.58989 11.3355 6.45446 11.2124L3.70446 8.71241C3.44905 8.48022 3.43023 8.08494 3.66242 7.82953C3.89461 7.57412 4.28989 7.55529 4.5453 7.78749L6.75292 9.79441L10.6018 3.90792C10.7907 3.61902 11.178 3.53795 11.4669 3.72684Z"
              fill="currentColor"
              fill-rule="evenodd"
              clip-rule="evenodd"
            ></path></svg></span
        ><span class="vui-steps-label-group"
          ><span class="vui-steps-label-base text-foreground">Account</span></span
        >
      </li>
      <span aria-hidden="true" class="vui-steps-connector-base bg-[var(--button-primary)]"></span>
      <li class="vui-steps-item" aria-current="step">
        <span
          class="vui-steps-marker-base border-[var(--button-primary)] text-[var(--button-primary)]"
          >2</span
        ><span class="vui-steps-label-group"
          ><span class="vui-steps-label-base text-foreground">Organization</span></span
        >
      </li>
      <span aria-hidden="true" class="vui-steps-connector-base bg-border"></span>
      <li class="vui-steps-item">
        <span class="vui-steps-marker-base border-border bg-background text-muted-foreground"
          >3</span
        ><span class="vui-steps-label-group"
          ><span class="vui-steps-label-base text-muted-foreground">Done</span></span
        >
      </li>
    </ol>
  </div>
  <div class="vui-wizard-body">
    <div class="space-y-4">
      <section class="vui-wizard-review-group">
        <div class="vui-wizard-review-header">
          <h3 class="vui-wizard-review-title">Organization</h3>
          <p class="vui-wizard-review-hint">Where you work.</p>
        </div>
        <div class="vui-wizard-review-body">
          <div class="vui-field-grid-root">
            <div class="vui-field-row">
              <label for="wizard-name" class="vui-field-label">Legal name</label>
              <div class="vui-field-control">
                <div class="vui-field-control-inner">
                  <input
                    class="flex h-11 w-full rounded-lg border border-input bg-background px-4 py-2.5 text-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background aria-invalid:border-destructive aria-invalid:focus-visible:ring-destructive disabled:cursor-not-allowed disabled:opacity-50 file:border-0 file:bg-transparent file:font-medium"
                    id="wizard-name"
                    value="Northwind Traders"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="vui-wizard-footer">
    <button
      type="button"
      class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-border bg-background text-foreground [&_svg]:text-muted-foreground hover:[&_svg]:text-foreground h-8 px-3"
    >
      <svg
        width="15"
        height="15"
        viewBox="0 0 15 15"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        class="vui-wizard-nav-icon"
      >
        <path
          d="M6.85355 3.14645C7.04882 3.34171 7.04882 3.65829 6.85355 3.85355L3.70711 7H12.5C12.7761 7 13 7.22386 13 7.5C13 7.77614 12.7761 8 12.5 8H3.70711L6.85355 11.1464C7.04882 11.3417 7.04882 11.6583 6.85355 11.8536C6.65829 12.0488 6.34171 12.0488 6.14645 11.8536L2.14645 7.85355C1.95118 7.65829 1.95118 7.34171 2.14645 7.14645L6.14645 3.14645C6.34171 2.95118 6.65829 2.95118 6.85355 3.14645Z"
          fill="currentColor"
          fill-rule="evenodd"
          clip-rule="evenodd"
        ></path></svg
      >Back</button
    ><button
      type="button"
      class="inline-flex cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-transparent bg-[var(--button-primary)] text-[var(--button-primary-foreground)] shadow-[var(--button-shadow)] hover:bg-[var(--button-primary-hover)] [&_svg]:border-[var(--button-primary-hover)] h-8 px-3"
    >
      Next<svg
        width="15"
        height="15"
        viewBox="0 0 15 15"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        class="vui-wizard-nav-icon"
      >
        <path
          d="M8.14645 3.14645C8.34171 2.95118 8.65829 2.95118 8.85355 3.14645L12.8536 7.14645C13.0488 7.34171 13.0488 7.65829 12.8536 7.85355L8.85355 11.8536C8.65829 12.0488 8.34171 12.0488 8.14645 11.8536C7.95118 11.6583 7.95118 11.3417 8.14645 11.1464L11.2929 8H2.5C2.22386 8 2 7.77614 2 7.5C2 7.22386 2.22386 7 2.5 7H11.2929L8.14645 3.85355C7.95118 3.65829 7.95118 3.34171 8.14645 3.14645Z"
          fill="currentColor"
          fill-rule="evenodd"
          clip-rule="evenodd"
        ></path>
      </svg>
    </button>
  </div>
</div>
